obj: exceptions spells spellbooks states units weapons classAbilities interface

exceptions:

interface:

classAbilities:
	g++ ../classAbility/ClassAbility.cpp -c
	g++ ../classAbility/VampireAbility.cpp -c
	g++ ../classAbility/WarlockAbility.cpp -c
	g++ ../classAbility/WerewolfAbility.cpp -c
	g++ ../classAbility/WolfAbility.cpp -c

spellbooks:
	g++ ../spellbook/SpellBook.cpp -c
	g++ ../spellbook/WizardSpellBook.cpp -c
	g++ ../spellbook/HealerSpellBook.cpp -c
	g++ ../spellbook/PriestSpellBook.cpp -c
	g++ ../spellbook/WarlockSpellBook.cpp -c
	g++ ../spellbook/NecromancerSpellBook.cpp -c

spells:
	g++ ../spell/Spell.cpp -c
	g++ ../spell/Fireball.cpp -c
	g++ ../spell/Heal.cpp -c

states:
	g++ ../state/State.cpp -c
	g++ ../state/MagicState.cpp -c
	g++ ../state/HumanState.cpp -c
	g++ ../state/UndeadState.cpp -c

	g++ ../state/VampireState.cpp -c
	g++ ../state/WerewolfState.cpp -c
	g++ ../state/WolfState.cpp -c
	g++ ../state/BerserkerState.cpp -c
	g++ ../state/SoldierState.cpp -c
	g++ ../state/RogueState.cpp -c
	g++ ../state/DemonState.cpp -c

	g++ ../state/WizardState.cpp -c
	g++ ../state/HealerState.cpp -c
	g++ ../state/PriestState.cpp -c
	g++ ../state/WarlockState.cpp -c
	g++ ../state/NecromancerState.cpp -c

	g++ ../state/WizardMState.cpp -c
	g++ ../state/HealerMState.cpp -c
	g++ ../state/PriestMState.cpp -c
	g++ ../state/WarlockMState.cpp -c
	g++ ../state/NecromancerMState.cpp -c

units:
	g++ ../unit/Unit.cpp -c
	g++ ../unit/SpellCaster.cpp -c
	g++ ../unit/Berserker.cpp -c
	g++ ../unit/Rogue.cpp -c
	g++ ../unit/Soldier.cpp -c
	g++ ../unit/Werewolf.cpp -c
	g++ ../unit/Vampire.cpp -c
	g++ ../unit/Wizard.cpp -c
	g++ ../unit/Warlock.cpp -c
	g++ ../unit/Demon.cpp -c
# 	g++ ../unit/*.cpp -c

weapons:
	g++ ../weapon/Weapon.cpp -c
	g++ ../weapon/Dagger.cpp -c
	g++ ../weapon/Sword.cpp -c
	g++ ../weapon/Fangs.cpp -c
	g++ ../weapon/Claws.cpp -c
	g++ ../weapon/TwoHandedSword.cpp -c
	g++ ../weapon/Mace.cpp -c
	g++ ../weapon/Staff.cpp -c
	g++ ../weapon/Scepter.cpp -c
	g++ ../weapon/HolyChimes.cpp -c
	g++ ../weapon/Chaplet.cpp -c
	g++ ../weapon/Sickle.cpp -c

clean:
	rm -rf *.o a.out a.exe